export const seedFounders = [
  { id: 'seed-1', full_name: 'Sarah Chen', handle: 'sarahbuilds', company: 'Ledgerline', role: 'CEO', stage: 'Seed', sector: 'Fintech', currently_figuring_out: 'How to price usage-based billing without scaring SMBs', avatar_url: 'https://i.pravatar.cc/120?img=47', traction: { raised: 1400000, mrr: 22000, mrrDelta: 31, hiring: 2 }, is_online: true },
  { id: 'seed-2', full_name: 'Marcus Webb', handle: 'mwebb', company: 'Synthflow', role: 'Founder', stage: 'Pre-seed', sector: 'AI/ML', currently_figuring_out: 'Whether to open-source the eval harness or keep it as moat', avatar_url: 'https://i.pravatar.cc/120?img=12', traction: { shipped: 'v2 agent runtime', hiring: 1 }, is_online: true },
  { id: 'seed-3', full_name: 'Priya Nair', handle: 'priyanair', company: 'Cohort', role: 'Co-founder', stage: 'Seed', sector: 'SaaS', currently_figuring_out: 'Reducing onboarding from 3 weeks to 3 days', avatar_url: 'https://i.pravatar.cc/120?img=32', traction: { raised: 2100000, mrr: 48000, mrrDelta: 18 }, is_online: false },
  { id: 'seed-4', full_name: 'Diego Ramirez', handle: 'diegor', company: 'Tarmac', role: 'CEO', stage: 'Series A', sector: 'Dev Tools', currently_figuring_out: 'Enterprise security reviews are killing our sales velocity', avatar_url: 'https://i.pravatar.cc/120?img=68', traction: { raised: 8500000, mrr: 190000, mrrDelta: 12, hiring: 4 }, is_online: true },
  { id: 'seed-5', full_name: 'Lena Okafor', handle: 'lenao', company: 'Verdant', role: 'Founder', stage: 'Pre-seed', sector: 'Climate', currently_figuring_out: 'Finding a technical co-founder who gets carbon markets', avatar_url: 'https://i.pravatar.cc/120?img=45', traction: { shipped: 'pilot with 2 utilities' }, is_online: false },
]

export const seedPosts = [
  { id: 'seed-post-1', author: seedFounders[0], body: 'Closed our seed \u2014 here\u2019s the deck math that worked: we anchored the raise on a single chart showing net revenue retention crossing 120%. Investors stopped asking about TAM the moment they saw expansion was real. Happy to share the slide structure with anyone raising now.', stage_tag: 'Seed', sector_tag: 'Fintech', traction_strip: { raised: 1400000, mrr: 22000, mrrDelta: 31 }, reaction_count: 24, reply_count: 6, created_at: new Date(Date.now() - 3600_000 * 4).toISOString(), isSeed: true },
  { id: 'seed-post-2', author: seedFounders[1], body: 'Hard pivot this week. Killed the consumer app, kept the inference layer underneath it. Turns out the thing nobody wanted to pay for was wrapping the thing everyone wanted to buy. Shipped a clean API in 9 days. Lesson: ship the substrate, not the surface.', stage_tag: 'Pre-seed', sector_tag: 'AI/ML', traction_strip: { shipped: 'v2 agent runtime' }, reaction_count: 41, reply_count: 11, created_at: new Date(Date.now() - 3600_000 * 9).toISOString(), isSeed: true },
  { id: 'seed-post-3', author: seedFounders[2], body: 'Cut onboarding time in half by deleting features. We removed the custom-workflow builder from the trial flow entirely. Activation jumped from 34% to 58% in two weeks. Sometimes the best feature work is subtraction. Anyone else seeing this with B2B trials?', stage_tag: 'Seed', sector_tag: 'SaaS', traction_strip: { raised: 2100000, mrr: 48000, mrrDelta: 18 }, reaction_count: 33, reply_count: 8, created_at: new Date(Date.now() - 3600_000 * 22).toISOString(), isSeed: true },
]
